services:
  # Service Backend (FastAPI)
  - type: web
    name: kairos-backend
    env: python
    region: frankfurt
    plan: starter
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: kairos
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://kairos-frontend-hjg9.onrender.com
      - key: REDIS_URL
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: "*"

  # Service Frontend (React/Vite) - Static Site
  - type: static
    name: kairos-frontend
    region: frankfurt
    buildCommand: cd frontend && npm ci && npm run build
    publishDirectory: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_URL
        value: https://kairos-0aoy.onrender.com/api
